# Generated by ChatGPT for versioned English tests

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0005_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
