from django.db import migrations


REVERSED_TESTS = {'Arab tili': {'0': [('صَدِيقٌ qanday o‘qiladi?', 'Sodiqun', 'Saduqun', 'Sidiqun', '—', 'A'),
                     ('فَصْلٌ qanday o‘qiladi?', 'Faslun', 'Fasilun', 'Fusulun', '—', 'A'),
                     ('جَمِيلٌ qanday o‘qiladi?', 'Jamīlun', 'Jumaylun', 'Jamalun', '—', 'A'),
                     ('مُدَرِّسٌ qanday o‘qiladi?', 'Mudarrisun', 'Madarrisun', 'Mudarrasun', '—', 'A'),
                     ('طَالِبٌ qanday o‘qiladi?', 'Tolibun', 'Tulibun', 'Talibun', '—', 'A'),
                     ('جَامِعَةٌ so‘zida nechta harf bor?', '4 ta', '5 ta', '6 ta', '—', 'C'),
                     ('سَيَّارَةٌ so‘zida nechta harf bor?', '5 ta', '6 ta', '7 ta', '—', 'C'),
                     ('حَدِيقَةٌ so‘zida nechta harf bor?', '5 ta', '6 ta', '7 ta', '—', 'B'),
                     ('مُسْتَشْفًى so‘zida nechta harf bor?', '5 ta', '6 ta', '7 ta', '—', 'C'),
                     ('اِجْتِهَادٌ so‘zida nechta harf bor?', '5 ta', '6 ta', '7 ta', '—', 'C'),
                     ('رٌ qanday tanvin?', 'Fathatan', 'Dammatan', 'Kasratan', '—', 'B'),
                     ('قٍ qanday tanvin?', 'Dammatan', 'Kasratan', 'Fathatan', '—', 'B'),
                     ('بً qanday tanvin?', 'Fathatan', 'Dammatan', 'Kasratan', '—', 'A'),
                     ('نُ qanday o‘qiladi?', 'Na', 'Nu', 'Ni', '—', 'B'),
                     ('مِ qanday o‘qiladi?', 'Mu', 'Ma', 'Mi', '—', 'C'),
                     ('Qaysi so‘zda sukunli harf mavjud?', 'شَمْسٌ', 'قَلَمٌ', 'وَلَدٌ', '—', 'A'),
                     ('Qaysi so‘zning oxiri ة bilan tugagan?', 'شَجَرَةٌ', 'بَابٌ', 'نَهْرٌ', '—', 'A'),
                     ('Qaysi so‘zda ikkita bir xil harf bor?', 'بَيْتٌ', 'تُفَّاحَةٌ', 'قَلَمٌ', '—', 'B'),
                     ('Qaysi so‘zda “ص” harfi qatnashgan?', 'قَلَمٌ', 'صَقْرٌ', 'كِتَابٌ', '—', 'B'),
                     ('Qaysi so‘z “ث” harfi bilan boshlanadi?', 'سَمَكٌ', 'ثَوْبٌ', 'شَمْسٌ', '—', 'B')],
               'A1': [('مُعَلِّمٌ so‘zining ayol jinsi qaysi?', 'مُعَلِّمَةٌ', 'مُعَلِّمُونَ', 'مُعَلَّمٌ', '—', 'A'),
                      ('Qaysi so‘z ko‘plikda kelgan?', 'وَلَدٌ', 'رِجَالٌ', 'قَلَمٌ', '—', 'B'),
                      ('Qaysi so‘z birlikda kelgan?', 'أَقْلاَمٌ', 'مُدَرِّسُونَ', 'بَيْتٌ', '—', 'C'),
                      ('طَالِبَةٌ so‘zining ko‘pligi qaysi?', 'طَالِبٌ', 'طَالِبَاتٌ', 'طُلاَّبٌ', '—', 'B'),
                      ('كِتَابٌ so‘zining ko‘pligi qaysi?', 'كُتُبٌ', 'كَاتِبٌ', 'مَكْتَبٌ', '—', 'A'),
                      ('Qaysi fe’l hozirgi zamonda?', 'كَتَبَ', 'يَكْتُبُ', 'اُكْتُبْ', '—', 'B'),
                      ('اِجْلِسْ qanday ma’noni bildiradi?', 'O‘tirdi', 'O‘tiradi', 'O‘tir!', '—', 'C'),
                      ('ذَهَبَ fe’li qaysi zamonda kelgan?', 'Hozirgi zamon', 'O‘tgan zamon', 'Buyruq mayli', '—', 'B'),
                      ('يَكْتُبُ fe’lining ma’nosi nima?', 'Yozadi', 'O‘qiydi', 'O‘tiradi', '—', 'A'),
                      ('Qaysi biri fe’l?', 'كِتَابٌ', 'يَذْهَبُ', 'طَالِبٌ', '—', 'B'),
                      ('“Men kitob o‘qiyman” gapining to‘g‘ri tarjimasi qaysi?',
                       'أَنا أَقْرَأُ الْكِتَابَ',
                       'أَنا يَقْرَأُ الْكِتَابَ',
                       'أَنا تَقْرَأُ الْكِتَابَ',
                       '—',
                       'A'),
                      ('Qaysi gapda fe’l to‘g‘ri ishlatilgan?',
                       'هُوَ تَكْتُبُ الدَّرْسَ',
                       'هِيَ يَكْتُبُ الدَّرْسَ',
                       'هُوَ يَكْتُبُ الدَّرْسَ',
                       '—',
                       'C'),
                      ('Qaysi gap to‘g‘ri?',
                       'الطُّلاَّبُ فِي الْفَصْلِ',
                       'الطُّلاَّبُ يَكْتُبُ',
                       'الطُّلاَّبُ أَقْرَأُ',
                       '—',
                       'A'),
                      ('Qaysi gap to‘g‘ri?',
                       'الْبِنْتُ الْجَمِيلُ',
                       'الْبِنْتُ الْجَمِيلَةُ',
                       'الْبِنْتُ جَمَالٌ',
                       '—',
                       'B'),
                      ('Qaysi gap grammatik jihatdan to‘g‘ri?',
                       'أَنا يَذْهَبُ إِلَى الْمَدْرَسَةِ',
                       'أَنا أَذْهَبُ إِلَى الْمَدْرَسَةِ',
                       'أَنا تَذْهَبُ إِلَى الْمَدْرَسَةِ',
                       '—',
                       'B'),
                      ('مَطَارٌ nimani bildiradi?', 'Bozor', 'Aeroport', 'Mehmonxona', '—', 'B'),
                      ('سَفَرٌ nimani bildiradi?', 'Sayohat', 'Dars', 'Uy', '—', 'A'),
                      ('سَرِيرٌ so‘zining ma’nosi nima?', 'Stol', 'Deraza', 'Karavot', '—', 'C'),
                      ('مَكْتَبَةٌ nimani bildiradi?', 'Kutubxona', 'Sinfxona', 'Oshxona', '—', 'A'),
                      ('مُهَنْدِسٌ so‘zining ma’nosi nima?', 'Shifokor', 'Muhandis', 'O‘qituvchi', '—', 'B')],
               'A2': [('Ular yangi loyiha boshlashdi:',
                       'أَكَلُوا الطَّعَامَ',
                       'بَدَأُوا مَشْرُوعًا جَدِيدًا',
                       'نَحْنُ نَقْرَأُ',
                       '—',
                       'B'),
                      ('Men arab tilini o‘rganmoqdaman:',
                       'أَتَعَلَّمُ اللُّغَةَ الْعَرَبِيَّةَ',
                       'أَكْتُبُ كِتَابًا',
                       'أَذْهَبُ إِلَى السُّوقِ',
                       '—',
                       'A'),
                      ('Biz ertaga sayohat qilamiz:',
                       'كُنَّا فِي الْبَيْتِ',
                       'سَنُسَافِرُ غَدًا',
                       'سَنَأْكُلُ غَدًا',
                       '—',
                       'B'),
                      ('U har kuni sport bilan shug‘ullanadi:',
                       'هُوَ يَمْرَسُ الرِّيَاضَةَ كُلَّ يَوْمٍ',
                       'هُوَ يَنَامُ',
                       'هُوَ يَأْكُلُ',
                       '—',
                       'A'),
                      ('Men kitobni diqqat bilan o‘qiyapman:',
                       'أَكْتُبُ الدَّرْسَ',
                       'أَقْرَأُ الْكِتَابَ بِانْتِبَاهٍ',
                       'أَذْهَبُ إِلَى السُّوقِ',
                       '—',
                       'B'),
                      ('Bu juda muhim qaror:',
                       'هُوَ يَقْرَأُ',
                       'هَذَا قَرَارٌ مُهِمٌّ جِدًّا',
                       'هَذَا كِتَابٌ جَدِيدٌ',
                       '—',
                       'B'),
                      ('Men kelajakda shifokor bo‘laman:',
                       'أَنَا طَالِبٌ',
                       'سَأَكُونُ طَبِيبًا',
                       'هُوَ مُدَرِّسٌ',
                       '—',
                       'B'),
                      ('Biz natijani tahlil qildik:',
                       'نَأْكُلُ فِي الْبَيْتِ',
                       'حَلَّلْنَا النَّتِيجَةَ',
                       'نَلْعَبُ فِي الْمَدْرَسَةِ',
                       '—',
                       'B'),
                      ('U loyiha ustida ishlamoqda:',
                       'هُوَ يَعْمَلُ عَلَى مَشْرُوعٍ',
                       'هُوَ يَأْكُلُ',
                       'هِيَ تَكْتُبُ',
                       '—',
                       'A'),
                      ('Men kecha juda charchagan edim:',
                       'سَأَذْهَبُ غَدًا',
                       'كُنْتُ مُتْعَبًا جِدًّا أَمْسِ',
                       'أَنَا أَقْرَأُ الْآنَ',
                       '—',
                       'B'),
                      ('مَا هَذَا؟', 'Qachon borasan?', 'Bu nima?', 'Qayerdasan?', '—', 'B'),
                      ('سَأَكُونُ مُعَلِّمًا:',
                       'Men o‘qituvchi bo‘laman',
                       'Men o‘qituvchiman',
                       'Men o‘qituvchi edim',
                       '—',
                       'A'),
                      ('هَلْ كُنْتَ فِي الْمَدْرَسَةِ؟',
                       'Sen borasanmi?',
                       'Sen maktabda edingmi?',
                       'Sen o‘qiyapsanmi?',
                       '—',
                       'B'),
                      ('لَمْ يَذْهَبْ إِلَى الْمَدْرَسَةِ:', 'U maktabga bormadi', 'U maktabda', 'U boradi', '—', 'A'),
                      ('كُنْتُ أَدْرُسُ فِي الْبَيْتِ ma’nosi:',
                       'Men maktabga boraman',
                       'Men o‘qiyapman',
                       'Men uyda o‘qirdim',
                       '—',
                       'C'),
                      ('قَضِيَّةٌ nima?', 'stol', 'kitob', 'masala / muammo', '—', 'C'),
                      ('تَحْلِيلٌ nima?', 'tahlil', 'o‘yin', 'yozuv', '—', 'A'),
                      ('إِعْلَامٌ nima?', 'suv', 'media / axborot', 'ovqat', '—', 'B'),
                      ('تَطْبِيقٌ nima?', 'uy', 'ilova / dastur', 'eshik', '—', 'B'),
                      ('اِسْتِقْلَالٌ nima?', 'sayohat', 'mustaqillik', 'kitob', '—', 'B')],
               'B1': [('أكمل: إنْ تجتهدْ ___ .', 'تنجحُ', 'تنجحْ', 'نجحتَ', 'نجاحًا', 'A'),
                      ('اختر الأسلوب التعجبي:', 'ما أجملَ السماءَ!', 'لا تكذبْ', 'هل حضرتَ؟', 'اجلسْ هنا', 'A'),
                      ('ما معنى "استفاد"؟', 'خسرَ', 'انتفعَ', 'غضبَ', 'تعبَ', 'B'),
                      ('أكمل: لم ___ الطالبُ الواجبَ.', 'يكتبُ', 'يكتبْ', 'كتبَ', 'كاتبًا', 'B'),
                      ('ما ضد كلمة "الكرم"؟', 'الجود', 'البخل', 'العطاء', 'الرحمة', 'B'),
                      ('اختر الجملة الصحيحة:',
                       'المسلمونَ متعاونونَ',
                       'المسلمينَ متعاونونَ',
                       'المسلمونَ متعاونينَ',
                       'المسلمينَ متعاونينَ',
                       'A'),
                      ('أيُّ الكلمات التالية اسمُ مكان؟', 'مكتب', 'كاتب', 'كتابة', 'مكتوب', 'A'),
                      ('أكمل: احترمِ الناسَ ___ يحترموكَ.', 'كي', 'حتى', 'لأنَّ', 'لكنَّ', 'A'),
                      ('اختر المعنى الصحيح: "تجاوزَ المشكلةَ"',
                       'صنعَ المشكلةَ',
                       'حلَّ المشكلةَ',
                       'تجاهلَ المشكلةَ',
                       'كررَ المشكلةَ',
                       'B'),
                      ('ما نوع "ليت"؟', 'حرف نصب', 'فعل', 'اسم', 'حرف جر', 'A'),
                      ('أكمل: ما زلتُ ___ عن الحقيقةِ.', 'أبحثُ', 'بحثتُ', 'باحثًا', 'أبحثْ', 'A'),
                      ('ما جمع كلمة "باحث"؟', 'باحثون', 'بواحث', 'أبحاث', 'بحثة', 'A'),
                      ('اختر الصحيح:',
                       'كانَ الجوُّ جميلًا',
                       'كانَ الجوُّ جميلٌ',
                       'كانَ الجوَّ جميلًا',
                       'كانَ الجوَّ جميلٌ',
                       'A'),
                      ('أكمل: إنَّ الطالبَيْنِ ___ الدرسَ.', 'فهموا', 'فهما', 'فهمَ', 'يفهمانِ', 'B'),
                      ('أيُّ الجمل التالية فيها أسلوب نهي؟',
                       'لا تتأخرْ عن الصلاةِ',
                       'ما أجملَ الصدقَ!',
                       'هل فهمتَ الدرسَ؟',
                       'ليت الشبابَ يعودُ',
                       'A'),
                      ('اختر المرادف: "شجاع"', 'جبان', 'قويُّ القلب', 'ضعيف', 'حزين', 'B'),
                      ('ما إعراب كلمة "سريعًا"؟ ركضَ الطفلُ سريعًا.', 'مفعول به', 'حال', 'خبر', 'نعت', 'B'),
                      ('أكمل: لو علمتُ الخبرَ مبكرًا ___ إليك.', 'لاتصلتُ', 'اتصلتُ', 'أتصلُ', 'سأتصلُ', 'A'),
                      ('اختر الجملة الصحيحة:',
                       'لم يذهبْ خالدٌ إلى المدرسةِ',
                       'لم يذهبُ خالدٌ إلى المدرسةِ',
                       'لم يذهبَ خالدٌ إلى المدرسةِ',
                       'لم يذهبْ خالدًا إلى المدرسةِ',
                       'A'),
                      ('ما معنى كلمة "ازدهار"؟', 'فقر', 'تقدم', 'مرض', 'خوف', 'B')]},
 'Hamshiralik': {'Hamshiralik 1': [('Burundan qon ketganda qaysi dori bilan burunga tampon qilinadi?',
                                    'Pereks vodorod bilan',
                                    'Zelyonka bilan',
                                    'Analgin dimedrol bilan',
                                    '—',
                                    'A'),
                                   ('Eng katta qon tomirdan qon ketishi nima deb ataladi?',
                                    'Venoz qon ketish',
                                    'Arteriyal qon ketish',
                                    'Kapilyar qon ketish',
                                    '—',
                                    'B'),
                                   ('Sun’iy nafas qachon beriladi?',
                                    'Klinik o‘limda',
                                    'Biologik o‘limda',
                                    'Hushdan ketganda',
                                    '—',
                                    'A'),
                                   ('Yurak o‘pka reanimatsiyasida massaj sohasi?',
                                    'Qovurg‘ani chap tomoni',
                                    'To‘sh sohasi pastki qismi',
                                    'Umurtqa pog‘onasi',
                                    '—',
                                    'B'),
                                   ('Hushdan ketganda qanday dori hidlatiladi?',
                                    'Pereks vodorod',
                                    'Yod',
                                    'Ammiak',
                                    '—',
                                    'C'),
                                   ('Stomatitda 1-yordam?',
                                    'Furatsilin va romashka bilan chayish',
                                    'Nistatin, imudon, kamistat gel',
                                    'Hammasi to‘g‘ri',
                                    '—',
                                    'C'),
                                   ('Stomatit qanday kasallik?',
                                    'Og‘iz bo‘shlig‘ini yallig‘lanishi',
                                    'Jigar yallig‘lanishi',
                                    'Kislorod yetishmasligi',
                                    '—',
                                    'A'),
                                   ('Anafilaktik shok nima?',
                                    'Yurak huruji',
                                    'Dorilardan reaksiya berishi',
                                    'Nafas yo‘liga yot jism turishi',
                                    '—',
                                    'B'),
                                   ('Nafas yo‘liga yot jism turib qolsa qaysi usuldan foydalaniladi?',
                                    'Robert Kox',
                                    'Gemlix',
                                    'Batalov',
                                    '—',
                                    'B'),
                                   ('Nafas soni bir minutda normada nechta bo‘ladi?',
                                    '16–20 ta',
                                    '60–90 ta',
                                    '30–40 ta',
                                    '—',
                                    'A'),
                                   ('Nafas bilan bog‘liq bo‘lgan muammoni qaysi shifokor davolaydi?',
                                    'Ginekolog',
                                    'Pulmonolog',
                                    'Kardiolog',
                                    '—',
                                    'B'),
                                   ('Pulsni tez urishi nima deyiladi?',
                                    'Bradikardiya',
                                    'Aritmiya',
                                    'Taxikardiya',
                                    '—',
                                    'C'),
                                   ('Puls normada bir minutda nechta uradi?', '90–120', '60–90', '16–20', '—', 'B'),
                                   ('Termometr sinishi xavflimi?',
                                    'Xavfli',
                                    'Xavfli emas',
                                    'To‘g‘ri javob yo‘q',
                                    '—',
                                    'A'),
                                   ('Tana harorati ko‘tarilganda, nechi gradusda ukol qilinmaydi?',
                                    '38–39 gradusda',
                                    '37–40 gradusda',
                                    '39–40 gradusda',
                                    '—',
                                    'B'),
                                   ('Tana harorati 38 bo‘lganda siz qanday yordam ko‘rsatasiz?',
                                    'Tabletka yoki suspenziya beraman',
                                    'Ineksiya qilaman',
                                    'Suv bilan badanini artib tushiraman',
                                    '—',
                                    'A'),
                                   ('Arteriyal qon bosim o‘lchaydigan asbob nima deyiladi?',
                                    'Termometr',
                                    'Pulsaksimetr',
                                    'Tanometr',
                                    '—',
                                    'C'),
                                   ('Qon bosim tushishi nima deyiladi?',
                                    'Gipertoniya',
                                    'Gipotermiya',
                                    'Gipotoniya',
                                    '—',
                                    'C'),
                                   ('Qon bosim oshganda birinchi yordam dorilar?',
                                    'Magneziya, dibazol, papaverin',
                                    'Analgin, dimedrol, deksametazon',
                                    'Kafein, magneziya',
                                    '—',
                                    'A'),
                                   ('Qon bosim ko‘tarilishi nima deyiladi?',
                                    'Gipotoniya',
                                    'Gipertoniya',
                                    'Gipertermiya',
                                    '—',
                                    'B')],
                 'Hamshiralik 2': [('O‘rta quloqdan o‘tgan nay qaysi halqumga tutashgan bo‘ladi?',
                                    'Og‘iz halqumi',
                                    'Burun halqumi',
                                    'Pastki halqum',
                                    '—',
                                    'B'),
                                   ('Quloq necha qismdan iborat?', '3 qismdan', '2 qismdan', '5 qismdan', '—', 'A'),
                                   ('Ko‘z tiniq bo‘lishi uchun qaysi vitaminni ko‘proq iste’mol qilish lozim?',
                                    'C vitamini',
                                    'A vitamini',
                                    'E vitamini',
                                    '—',
                                    'B'),
                                   ('Ko‘zdagi kolbachasimon hujayralar vazifasi nima?',
                                    'Kunduzi ko‘rishni ta’minlaydi',
                                    'Tunda ko‘rishni ta’minlaydi',
                                    'Nurni sindirib o‘tkazadi',
                                    '—',
                                    'A'),
                                   ('Bolaning o‘smay qolishi nima deb ataladi?',
                                    'Akromegaliya',
                                    'Somatotrof',
                                    'Nanizm',
                                    '—',
                                    'C'),
                                   ('O‘ng yarimshar dunyoni nima bilan anglaydi?',
                                    'So‘z bilan',
                                    'Ko‘z bilan',
                                    'To‘g‘ri javob yo‘q',
                                    '—',
                                    'B'),
                                   ('Taloq qaysi tomonda joylashgan?',
                                    'Chap tomonda',
                                    'O‘ng tomonda',
                                    'O‘rtada',
                                    '—',
                                    'A'),
                                   ('Trombotsit vazifasi?',
                                    'Qonni quyuq-suyuq qiluvchi modda ishlab beradi',
                                    'Qonga qizil rang beradi',
                                    'Virusdan himoya qiladi',
                                    '—',
                                    'A'),
                                   ('Testosteron qanday gormon?',
                                    'Ayollar gormoni',
                                    'Homiladorlar gormoni',
                                    'Erkaklar gormoni',
                                    '—',
                                    'C'),
                                   ('Miyachaning vazifasi?',
                                    'Muvozanatni saqlash',
                                    'Ta’m bilish',
                                    'Dofamin ishlab chiqish',
                                    '—',
                                    'A'),
                                   ('Buyrak ichidagi filtr nima deb ataladi?',
                                    'Kapsula',
                                    'Varsinkalar',
                                    'Nefronlar',
                                    '—',
                                    'C'),
                                   ('Qaysi qon tomirda karbonat angidrid bo‘ladi?',
                                    'Arteriya',
                                    'Vena',
                                    'To‘g‘ri javob yo‘q',
                                    '—',
                                    'B'),
                                   ('Yurakning qaysi tomonida kislorodga to‘la qon oqadi?',
                                    'O‘ng tomonda',
                                    'Chap tomonda',
                                    'To‘g‘ri javob yo‘q',
                                    '—',
                                    'B'),
                                   ('Yurak nechta kameradan iborat?', '4 ta', '5 ta', '6 ta', '—', 'A'),
                                   ('Jigar qaysi tomonda joylashgan?',
                                    'Chap tomonda',
                                    'O‘rtada',
                                    'O‘ng tomonda',
                                    '—',
                                    'C'),
                                   ('Ingichka ichakdagi so‘rg‘ichlar nima deyiladi?',
                                    'Ko‘richak',
                                    'Varsinkalar',
                                    'Xlorid kislota',
                                    '—',
                                    'B'),
                                   ('Ikkita o‘pkada alviyolalar soni nechta?', '750 ml', '840 ml', '650 ml', '—', 'A'),
                                   ('Traheyadan nima o‘tadi?', 'Kislorod', 'Ovqat', 'Qon', '—', 'A'),
                                   ('Bizni jilmayishimiz uchun nechta mushak ishlaydi?',
                                    '80 ta',
                                    '43 ta',
                                    '17 ta',
                                    '—',
                                    'C'),
                                   ('Eng katta suyak?',
                                    'Naysimon suyak',
                                    'Son suyagi',
                                    'O‘rta quloq eshituv suyagi',
                                    '—',
                                    'B')]}}


def seed_reversed_arab_hamshiralik_tests(apps, schema_editor):
    Subject = apps.get_model('olympiad', 'Subject')
    Level = apps.get_model('olympiad', 'Level')
    Question = apps.get_model('olympiad', 'Question')

    for subject_name, levels in REVERSED_TESTS.items():
        subject, _ = Subject.objects.get_or_create(name=subject_name)
        for level_name, questions in levels.items():
            level, _ = Level.objects.get_or_create(
                subject=subject,
                name=level_name,
                defaults={'duration_minutes': 30},
            )
            Question.objects.filter(subject=subject, level=level).delete()
            Question.objects.bulk_create([
                Question(
                    subject=subject,
                    level=level,
                    version=1,
                    text=text,
                    option_a=a,
                    option_b=b,
                    option_c=c,
                    option_d=d,
                    correct_answer=correct,
                )
                for text, a, b, c, d, correct in questions
            ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0009_seed_frontend2_javascript_tests'),
    ]

    operations = [
        migrations.RunPython(seed_reversed_arab_hamshiralik_tests, noop_reverse),
    ]
